name: CI
on:
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .nvmrc
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test-node
      - run: yarn examples:typecheck
      - run: yarn website:build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: website
          path: website/build
  gpu-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .nvmrc
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn playwright install --with-deps chromium
      - run: yarn test-headless
